Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from osipi_code_collection.wrappers.tofts import tofts_fit, show_maps, show_error_maps
from osipi_code_collection.utils.nb import download_osf, loadmat
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/tmp/ipykernel_1964/2891612316.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0mosipi_code_collection[0m[0;34m.[0m[0mwrappers[0m[0;34m.[0m[0mtofts[0m [0;32mimport[0m [0mtofts_fit[0m[0;34m,[0m [0mshow_maps[0m[0;34m,[0m [0mshow_error_maps[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mfrom[0m [0mosipi_code_collection[0m[0;34m.[0m[0mutils[0m[0;34m.[0m[0mnb[0m [0;32mimport[0m [0mdownload_osf[0m[0;34m,[0m [0mloadmat[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/osipi_code_collection/wrappers/tofts.py[0m in [0;36m<module>[0;34m[0m
[1;32m      5[0m [0;32mfrom[0m [0mscipy[0m[0;34m.[0m[0moptimize[0m [0;32mimport[0m [0mcurve_fit[0m[0;34m[0m[0;34m[0m[0m
[1;32m      6[0m [0;31m# osipi utilities[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 7[0;31m [0;32mfrom[0m [0mosipi[0m[0;34m.[0m[0mutils[0m[0;34m.[0m[0mnb[0m [0;32mimport[0m [0mpercenterror[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m [0;31m# osipi implementations[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      9[0m [0;32mimport[0m [0mosipi[0m[0;34m.[0m[0moriginal[0m[0;34m.[0m[0mLEK_UoEdinburghUK[0m[0;34m.[0m[0mPharmacokineticModelling[0m[0;34m.[0m[0mmodels[0m [0;32mas[0m [0medinburgh1[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'osipi'
ModuleNotFoundError: No module named 'osipi'

